package dk.easv.blsgn.intgrpbelsign.utils;

import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.*;
import com.itextpdf.layout.*;
import com.itextpdf.layout.element.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.ArrayList;



public class PdfReportGenerator {

    // ✅ This method returns the PDF as a byte[]
    public static byte[] generateSimplePdfToBytes(String orderNumber, String itemName) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        generateSimplePdf(orderNumber, itemName, baos);
        return baos.toByteArray();
    }

    // 🛠️ Internal method to build the PDF
    private static void generateSimplePdf(String orderNumber, String itemName, OutputStream out) throws IOException {
        PdfWriter writer = new PdfWriter(out);
        PdfDocument pdf = new PdfDocument(writer);
        Document doc = new Document(pdf);

        doc.add(new Paragraph("Order Report"));
        doc.add(new Paragraph("Order Number: " + orderNumber));
        doc.add(new Paragraph("Item: " + itemName));
        doc.add(new Paragraph("Generated by QC Department"));

        doc.close();
    }


    public static byte[] generatePdfWithImages(String orderNumber, String itemName, List<byte[]> imageList) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PdfWriter writer = new PdfWriter(baos);
        PdfDocument pdf = new PdfDocument(writer);
        Document doc = new Document(pdf);

        doc.add(new Paragraph("Order Report").setBold().setFontSize(18));
        doc.add(new Paragraph("Order Number: " + orderNumber));
        doc.add(new Paragraph("Item: " + itemName));
        doc.add(new Paragraph("Date: " + java.time.LocalDate.now()));
        doc.add(new Paragraph("\n"));

        for (int i = 0; i < imageList.size(); i++) {
            byte[] imgBytes = imageList.get(i);
            if (imgBytes != null) {
                ImageData imageData = ImageDataFactory.create(imgBytes);
                Image image = new Image(imageData).scaleToFit(400, 300);
                doc.add(new Paragraph("Image " + (i + 1)));
                doc.add(image);
            }
        }

        doc.close();
        return baos.toByteArray();
    }
}